project:
  type: website
  output-dir: docs
  
website:
  title: "JRHA"
  favicon: media/logo.png
  site-url: "https://jramonha.github.io"
  description: "Personal website for Jose Ramon Hernandez Aguilar"
  search: false
  navbar:
     right:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd
      - cv.qmd
      - text: <i class="bi bi-linkedin"></i>
        href: https://www.linkedin.com/in/jrhaguilar/
      - text: <i class="bi bi-github"></i>
        href: https://github.com/JRamonHA
  page-footer:
    left: |
      License: [CC BY NC SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0).
    center: |
      <i class="bi bi-c-circle"></i>
      2025, José Ramón Hernández Aguilar
    right: |
      Made with [{{< iconify simple-icons:quarto title="Quarto Logo" label="Quarto Logo" >}} Quarto](https://quarto.org)
  twitter-card:
    image: "media/preview.png"
    card-style: "summary_large_image"
    creator: "@JRamon_HA"
    site: "@JRamon_HA"
  open-graph: true

format:
  html:
    theme: 
    - theme.scss
    css: css/styles.css  
    mainfont: Raleway
    metadata:
      pagetitle: "JRHA"

lightbox: true
