project:
  type: website
  output-dir: docs
  
website:
  favicon: images/logo.png
  site-url: "https://jramonha.github.io"
  title: "JRHA"
  navbar:
     right:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd
      - cv.qmd

      - text: <i class="bi bi-linkedin"></i>
        href: https://www.linkedin.com/in/jrhaguilar/
      - text: <i class="bi bi-github"></i>
        href: https://github.com/JRamonHA
  page-footer:
    left: |
      License: [CC BY NC SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0).
    center: |
      <i class="bi bi-c-circle"></i>
      2025, José Ramón Hernández Aguilar
    right: |
      Made with [{{< iconify simple-icons:quarto title="Quarto Logo" label="Quarto Logo" >}} Quarto](https://quarto.org)

format:
  html:
    theme: 
    - theme.scss 
    mainfont: Raleway
    css: css/styles.css 
    metadata:
      pagetitle: "JRHA"

lightbox: auto
